applicationRegion      = "us-east-1"
projectName            = "bookShopApplication"
vpc_CIDR               = ""
pub_Sub_1_A_CIDR       = ""
pub_Sub_2_B_CIDR       = ""
pri_Sub_3_A_CIDR       = ""
pri_Sub_4_B_CIDR       = ""
pri_Sub_5_A_CIDR       = ""
pri_Sub_6_B_CIDR       = ""
DBUserName             = ""
DBPassword             = ""

CertificateDomainName  = ""
AdditionalDomainName   = ""
